title: Dana C'Julio
logo: /assets/img/logo.jpg
description: dana.cjulio@auckland.ac.nz <br><br> 2020-Present: PhD in Applied Mathematics<br>University of Aucklad,<br> New Zealand<br><br>2010-2019: Mathematical Engineer <br> Universidad Federico Santa Maria<br>Valparaiso, Chile. 
#show_downloads: true 
theme: jekyll-theme-minimal
